# DigitalOcean App Platform — MIbisnes
# Ветка для деплоя: App Platform (или main — укажите свою в github.branch)

name: mibisnes

static_sites:
  - name: mibisnes-web
    environment_slug: node-js
    build_command: npm ci && npm run build
    output_dir: dist
    github:
      repo: wrapzone722-commits/MIBisnes
      branch: main
      deploy_on_push: true
